name: Auto Sort Channels
on:
  push:
  schedule:
    - cron: '0 */6 * * *' # يتم التحديث تلقائياً كل 6 ساعات

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Sorter
        run: python sort_channels.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add channels.json
          git commit -m "Update sorted channels" || exit 0
          git push
